buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        // AGP חייב לתמוך ב-compileSdk שנבחר למטה - עדכנו יחד
        classpath 'com.android.tools.build:gradle:8.5.2'
    }
}

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}
